### ISSUE TITLE
Incorrect name for extract command

### ISSUE THREAD

**Issue by sbruchmann** [dbratcher/brackets-extract#1]
Hi Drew,

the name for the `me.drewbratcher.extract`-command, which is defined at [main.js#L118](https://github.com/dbratcher/brackets-extract/blob/a137c0fd80afb47d108a79aff3d528ebb5150677/main.js#L118), should be ‘Extract’.

**Comment by dbratcher** [comment]
Nice catch, thanks for starting the localization refactoring too. The pull request is up on the registry.
