### ISSUE TITLE
Suggestions: Extract undefined variables to parameters

### ISSUE THREAD

**Issue by hacker112** [dbratcher/brackets-extract#7]
This extension would be much more useful if any undefined var in the selected text would be added as parameters. 
Now I have to add those parameters manually when I move the function outside the scope where those variables where defined.

**Comment by dbratcher** [comment]
@hacker112  Thanks for the feature request, this was a really good idea. First pass at this feature is complete in 4712b47bf32a7518e9aaf76605e79a53f1c92d7e and deployed on the registry. Open new bug tickets if it doesn't work as expected.
