### ISSUE TITLE
Extract variables to function does not work completely

### ISSUE THREAD

**Issue by hacker112** [dbratcher/brackets-extract#8]
Examples that does not work (extracted part are marked by *):

Should extract a, but extracts throw
            var a = new Error('Some error');
-            throw a;

Should extract a.
-            var x = a;
-            x.callSomething();

Should extract x, but extracts return.
-            var x = 1;
-            return x;
  Should result in (note the extra return on extract):
  function extracted() {
  var x = 1;
  return x;
  } 
  return extracted(x);

And by the way extracted function should have a semicolon to be able to to minimized (pass JSHint/JSLint).

**Comment by dbratcher** [comment]
fixed these scenarios in version 1.3.2 now up on the registry, and a few other issues too. 

note the semicolon is only included if its the last character in the extracted text
also note the return is only included if its in the last line of the right trimmed extracted text

open new issues for future scenarios, reopen this issue if one of these scenarios is not handled correctly
