### ISSUE TITLE
There is always more ;)

### ISSUE THREAD

**Issue by hacker112** [dbratcher/brackets-extract#9]
I tried the tool again today (newest version):

Now if, else, and instanceof go extracted too.

``` javascript
            function extracted(controller, before,
                if, instanceof, beforeActions,
                else) {
                var controllerBefore = controller.controller.before;
                if (controllerBefore !== undefined) {
                    if (controllerBefore instanceof Array) {
                        beforeActions = beforeActions.concat(controllerBefore);
                    } else {
                        beforeActions.push(controllerBefore);
                    }
                };
            }
            extracted(controller, before,
                if, instanceof, beforeActions,
                else);
```

If I find the time I will fork the code and try to improve it :) 
I see that you have no tests, I think that could be good in order not to break something that worked before :-)
And some kind of Abstract Syntax Tree (AST) would be good for the analyzing the data.

**Comment by dbratcher** [comment]
@hacker112 those are some good ideas, I'll implement tests as part of this issue, and make some representative tests for other use cases. I opened issue 10 for the AST feature, I'm not really interested in implementing that right now, but I think it would be a good addition.
